version: '3.8'

services:
  qr-generator:
    image: nginx:alpine
    container_name: qr-generator
    ports:
      - "8080:80" # Puedes cambiar el puerto 8080 por el que prefieras
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: always
